apiVersion: apps/v1
kind: Deployment
metadata:
  name: bidding-engine
  namespace: food-delivery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bidding-engine
  template:
    metadata:
      labels:
        app: bidding-engine
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        envFrom:
        - configMapRef:
            name: advertisement-config
        image: food-delivery/bidding-engine:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/liveness
            port: 8102
          initialDelaySeconds: 45
          periodSeconds: 10
        name: bidding-engine
        ports:
        - containerPort: 8102
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/indexBootstrap
            port: 8102
          initialDelaySeconds: 30
          periodSeconds: 5
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
